# Extract and Filter Data from Excel File using Python.
**Author:**
Brahim Zirari <br>
**Version:**
Python 3.13.5 <br>
**Topic:** Creating a Filtered Sub-Excel File from a Large Dataset Containing Only Selected Countries and Variables. <br>
**Selected countries:** Algeria, Malaysia, and Saudi Arabia <br>
**Selected variable:** Statistical performance indicators (SPI) <br>
**Excel Dataset** Link. <a href = "https://www.kaggle.com/datasets/brahimzr/statistical-performance-indicator" > Click here </a>

In [9]:
#Working file info
file_path = r"C:\Users\Brahim\Downloads\statistical-performance-indicator.csv"  #Your csv file path

#Importing and loading DATA
import pandas as pd
df = pd.read_csv(file_path)

#Filter criteria
selected_countries = ["Algeria","Malaysia","Saudi Arabia"]
selected_variable = "Statistical performance indicators (SPI): Overall score (scale 0-100)"  # Choose the variable you need
output_file = "filtered_SPI.xlsx"  # Output file name

#Filter Selected Sata
filtered_df = df[
    df["Entity"].isin(selected_countries)
    ]

#Sort by Entity and Year
filtered_df = filtered_df.sort_values(["Entity", "Year"])

#Display the filtered data
print("Filtered Data:")
display(filtered_df)

#SAVE TO EXCEL
filtered_df.to_excel(output_file, index=False)

Filtered Data:

,Entity,Code,Year,Statistical performance indicators (SPI): Overall score (scale 0-100)
16,Algeria,DZA,2016,45.060417
17,Algeria,DZA,2017,49.204582
18,Algeria,DZA,2018,56.248333
19,Algeria,DZA,2019,58.652500
20,Algeria,DZA,2020,54.076250
21,Algeria,DZA,2021,64.804170
22,Algeria,DZA,2022,62.236668
23,Algeria,DZA,2023,62.692917
750,Malaysia,MYS,2016,61.340416
751,Malaysia,MYS,2017,62.525833
752,Malaysia,MYS,2018,70.444170
753,Malaysia,MYS,2019,68.880420
754,Malaysia,MYS,2020,70.767080
755,Malaysia,MYS,2021,74.756250
756,Malaysia,MYS,2022,76.161670
757,Malaysia,MYS,2023,80.417915
1094,Saudi Arabia,SAU,2016,40.698750
1095,Saudi Arabia,SAU,2017,45.226665
1096,Saudi Arabia,SAU,2018,53.125000
1097,Saudi Arabia,SAU,2019,57.718750
1098,Saudi Arabia,SAU,2020,65.330414
1099,Saudi Arabia,SAU,2021,72.302500
1100,Saudi Arabia,SAU,2022,74.387085
1101,Saudi Arabia,SAU,2023,81.533330